version: '2'

services:

  calculator:
      image: 192.168.1.151:32000/calculator:1.11.102
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
