version: '2'

services:

  calculator:
      image: neon-registry.b4c5-2917-0fd3-88a5.neoncluster.io/leenet/calculator:1.11.97
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
